About page added.
opencode18/OpenTerm pull request #21
Opened 2018-01-21 22:24 UTC by falconis

#15 I created the about on my own. If the text is something else please let me know. I'll update it
[link](https://falconis.github.io/OpenTerm/l)

2018-01-22 19:33 UTC, gauthamzz requested changes
![deepinscreenshot_select-area_20180123010221](https://user-images.githubusercontent.com/12110844/35240344-1e77c578-ffd9-11e7-8547-b65410a4b9f1.png)

Why is it half black ?

I feel like there is a lot of free space on top,unwanted.

2018-01-24 13:32 UTC, falconis commented
The black bar was just for decoration. I'll remove that. I'll also fozt the vertical spacing. I was actually trying to match the orientation of the terminal

2018-01-29 13:51 UTC, falconis commented
Made some changes. I hope they are according to your liking. Pls review @gauthamzz .

2018-01-29 14:50 UTC, gauthamzz approved these changes

2018-01-29 14:50 UTC, merged